spring:
  application:
    name: KotlinSpringLive
  r2dbc:
    url: r2dbc:postgresql://192.168.0.153:5432/postgres
    username: root
    password: Aa123456
    pool:
      enabled: true
      max-idle-time: 30m
  data:
    redis:
      host: 192.168.0.153
      port: 6379
      database: 0
  jackson:
    serialization:
      write-null-map-values: false